In [1]:
import pandas as pd
import numpy  as np
data = pd.read_csv("lung.csv", header=0).values

In [2]:
data

array([[0, 'P1', 33, ..., 3, 4, 'Low'],
       [1, 'P10', 17, ..., 7, 2, 'Medium'],
       [2, 'P100', 35, ..., 7, 2, 'High'],
       ...,
       [997, 'P997', 25, ..., 7, 2, 'High'],
       [998, 'P998', 18, ..., 2, 3, 'High'],
       [999, 'P999', 47, ..., 7, 2, 'High']], dtype=object)

In [3]:
a,b = np.unique(data[:,-1], return_counts=True)
print(a,b)

['High' 'Low' 'Medium'] [365 303 332]


In [4]:
data.shape

(1000, 26)

In [78]:
np.unique(data[:,24])

array([1, 2, 3, 4, 5, 6, 7], dtype=object)

In [41]:
'''
level = {
    'Low'    : 0,
    'Medium' : 1,
    'High'   : 2
}
data[:,-1] = [level[val] for val in data[:,-1]]
'''

"\nlevel = {\n    'Low'    : 0,\n    'Medium' : 1,\n    'High'   : 2\n}\ndata[:,-1] = [level[val] for val in data[:,-1]]\n"

In [42]:
dt = data[:,2:26]
dt

array([[33, 1, 2, ..., 3, 4, 'Low'],
       [17, 1, 3, ..., 7, 2, 'Medium'],
       [35, 1, 4, ..., 7, 2, 'High'],
       ...,
       [25, 2, 4, ..., 7, 2, 'High'],
       [18, 2, 6, ..., 2, 3, 'High'],
       [47, 1, 6, ..., 7, 2, 'High']], dtype=object)

In [43]:
#dt = dt.astype(int)

In [44]:
dt.shape

(1000, 24)

In [45]:
X = dt[:,0:23]
y = dt[:,-1]

In [46]:
from sklearn.model_selection import train_test_split

# Chia dữ liệu train, test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [47]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Tạo mô hình KNN với k=3 (hoặc số lân cận bạn muốn sử dụng)
k = 5
knn_model = KNeighborsClassifier(n_neighbors=k)

# Huấn luyện mô hình KNN trên tập huấn luyện
knn_model.fit(X_train, y_train)

# Dự đoán kết quả trên tập kiểm tra
y_pred = knn_model.predict(X_test)

# Tính độ chính xác của mô hình trên tập kiểm tra
accuracy = accuracy_score(y_test, y_pred)
print("Độ chính xác của mô hình KNN trên tập kiểm tra:", accuracy)

Độ chính xác của mô hình KNN trên tập kiểm tra: 0.995


In [48]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

# Tạo mô hình Naive Bayes
naive_bayes_model = GaussianNB()

# Huấn luyện mô hình trên tập huấn luyện
naive_bayes_model.fit(X_train, y_train)

# Dự đoán kết quả trên tập kiểm tra
y_pred = naive_bayes_model.predict(X_test)

# Tính độ chính xác của mô hình trên tập kiểm tra
accuracy = accuracy_score(y_test, y_pred)
print("Độ chính xác của mô hình Naive Bayes trên tập kiểm tra:", accuracy)

Độ chính xác của mô hình Naive Bayes trên tập kiểm tra: 0.895


In [49]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Tạo mô hình Random Forest
random_forest_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Huấn luyện mô hình trên tập huấn luyện
random_forest_model.fit(X_train, y_train)

# Dự đoán kết quả trên tập kiểm tra
y_pred = random_forest_model.predict(X_test)

# Tính độ chính xác của mô hình trên tập kiểm tra
accuracy = accuracy_score(y_test, y_pred)
print("Độ chính xác của mô hình Random Forest trên tập kiểm tra:", accuracy)

Độ chính xác của mô hình Random Forest trên tập kiểm tra: 1.0


In [50]:
import joblib

#joblib.dump(random_forest_model, 'models.pkl')

In [51]:
# Gọi mô hình
models = joblib.load('models.pkl')

In [52]:
new_data = [[24,1,6,8,7,7,6,7,7,3,8,7,9,6,5,2,5,2,3,2,1,7,6]]
models.predict(new_data)[0]

'High'